### ISSUE TITLE
Test matrix complexity

### ISSUE THREAD

**Issue by aviks** [JuliaInterop/JavaCall.jl#127]
I want to test this package with JDK8 and JDK11 (and more in the future). The following invocation in the Travis config does that 

```
dist: bionic
env:
  - JAVA_HOME=/usr/local/lib/jvm/openjdk8
  - JAVA_HOME=/usr/local/lib/jvm/openjdk11
```

However, the test matrix is already very complex, and I'm not sure if adding more dimensions to it is a good idea. 

Should we go ahead nevertheless? Or should we remove windows testing from Travis, and just use appveyor for windows? Should we look into github actions?

cc: @mkitti

**Comment by mkitti** [comment]
For Travis, we should look into using their jdk_switcher script: https://docs.travis-ci.com/user/languages/java/ . Within a single run, we could run tests on multiple JDKs. The situation is also pretty complicated between Linux and Mac. By the way, I think it is possible to test configurations on Travis itself without pushing commits to github.

Another way to manage Travis is to have distinct branches configured to test specific JDK versions. That would also make per-version fixes easier should that become necessary.

For JDK 9+, we need to do some tests for `GetModule`

Exploring Github would also be handy.

**Comment by mkitti** [comment]
This tool can be used to test Travis configurations:
https://config.travis-ci.com/explore

**Comment by mkitti** [comment]
@aviks I have enabled explicit JDK8 and JDK11 testing on Linux and explicit JDK8 testing on Mac using the Travis jobs / include directive:
https://travis-ci.org/github/JuliaInterop/JavaCall.jl/builds/702735910

I might remove the explicit testing for JDK11 since JDK11 is currently the default for Linux.

I'll see what I can do with Windows.

**Comment by mkitti** [comment]
Now testing OpenJDK8 on Windows: https://travis-ci.org/github/JuliaInterop/JavaCall.jl/jobs/702759326

**Comment by mkitti** [comment]
Do we plan on merging #124 soon or should I port `.travis.yml` and `test/windows_java.sh` over to master?

**Comment by mkitti** [comment]
I commited the testing changes to master: https://github.com/JuliaInterop/JavaCall.jl/commit/8d33e56d9544056917450707147bb527c835bc32
