### ISSUE TITLE
jvoid missing in JavaCall v0.7.7

### ISSUE THREAD

**Issue by bardo84** [JuliaInterop/JavaCall.jl#153]
Hi,
using your [jmathplot ](https://discourse.julialang.org/t/jmathplot-via-javacall-jl/69686)example
and
 [494afd89] JavaCall v0.7.7 installed, I get
ERROR: LoadError: UndefVarError: jvoid not defined
temp fix using
jvoid = Nothing

BTW 1)
jcall(frame, "pack", jvoid)
ERROR: MethodError: no method matching jcall(::JavaObject{Symbol("javax.swing.JFrame")}, ::String, ::Type{jvoid})

BTW 2)
How to conditionally avoid
ERROR: LoadError: JavaCall.JavaCallError("JVM already initialised")

BTW 3)
The whole jmathplot effort was to have a lightweight drawing pane (text, line) allowing interactivity and possibly callbacks.
Do you have something in this direction?

Thx again!

**Comment by mkitti** [comment]
Just use `Nothing` for `jvoid`.

1) `jcall(frame, "pack", jvoid, ())`
2) Check `JavaCall.isloaded()` before calling `JavaCall.init()`
3) In Julia? Sure. Plenty. I might start with [Plots.jl](http://docs.juliaplots.org/latest/) using either the GR or PyPlot backends. If you need something very light weight, I would consider using [GR.jl](https://gr-framework.org/julia.html) directly or [GRUtils.jl](https://heliosdrm.github.io/GRUtils.jl/latest/). You might consider [combining GR.jl with QT / QML.jl](https://github.com/barche/QmlJuliaExamples/blob/master/canvas_and_gr.jl). If you want something more, I would suggest [Makie.jl](https://github.com/JuliaPlots/Makie.jl). There are also several wrappers around GNUPlot such as [Gaston.jl](https://github.com/mbaz/Gaston.jl)

It's probably best to ask these kind of questions on Discourse. You might also try searching for answers there as well.

**Comment by bardo84** [comment]
3x thank you!
I know all these packages. 
My quest for a drawing pane allowing interactivity is more for low-level.
Now every package depends on one drawing backend, does something right but misses another feature, 
Like Plots.jl translates a common plot syntax to various backends, I wonder if it could make sense to provide an interface at the lowest drawing level. Then one could separate the elaborated scaling/margin/grouping/updating from the actual physical drawing backend.
