### ISSUE TITLE
Thoughts on JuliaInterop org

### ISSUE THREAD

**Issue by MikeInnes** [JuliaInterop/JavaCall.jl#26]
Was just wondering if you think it's worth consolidating a few of the interop packages under one org – there are at least 6 by my count and it might be nice to show them off together.

**Comment by aviks** [comment]
Personally I am not sold on the benefits of one org, but am not vehemently opposed either.  So happy to move this if an org is created.

**Comment by ViralBShah** [comment]
I personally think that having this in the JuliaInterop organization makes sense. Other discussion here: https://github.com/Keno/Cxx.jl/issues/291

We can always move it to something else in the future, but having a solid list of languages that we support interop with in one org is a powerful signal in my mind.
