### ISSUE TITLE
How to load a custom class?

### ISSUE THREAD

**Issue by quinnj** [JuliaInterop/JavaCall.jl#53]
I'm probably missing something obvious here.......
```julia
julia> jcall(jlm, "getAlertCountByOwnerId", jlong, (JString,), "1")
ERROR: Class Not Found com/domo/api/alerts/v3/impl
 in _metaclass(::Symbol) at /Users/jacobquinn/.julia/v0.5/JavaCall/src/core.jl:233
 in metaclass(::Symbol) at /Users/jacobquinn/.julia/v0.5/JavaCall/src/core.jl:239
 in jcall(::Type{JavaCall.JavaObject{Symbol("com.domo.api.alerts.v3.impl")}}, ::String, ::Type{T}, ::Tuple{DataType}, ::String, ::Vararg{String,N}) at /Users/jacobquinn/.julia/v0.5/JavaCall/src/core.jl:129
```

This is just a random class that should be "running"/loaded. What's the process for calling a custom class?

**Comment by aviks** [comment]
You need to add that class to the Java _classpath_ before the JVM is initialised. The simplest way is to pass a parameter to the `init` method. 

```julia
JavaCall.init(["-Djava.class.path=/path/to/package.jar;/path/to/anotherpackage.jar"])
```

Another way to do the same thing is to call `addClasspath` before calling `init`

```
JavaCall.addClassPath("/path/to/package.jar")
JavaCall.addClassPath("/path/to/anotherpackage.jar")
JavaCall.init()
```

**Comment by aviks** [comment]
Hi @quinnj did this work for you?

**Comment by aviks** [comment]
This should work as intended. Please reopen if no.

**Comment by Eyota** [comment]
I have the same problem, but didn't manage to solve it this way... Am I still missing something?

Java Class: Outer.java
`package mypackage;

public class Outer {
    public class Inner{
        public void innerMethod() {
            System.out.println("In Inner class Method");
        }
    }
    public Inner createrInnerObject() {
        Inner innerObj=new Inner();
        return innerObj;
    }
}
`
Julia file: 
`using JavaCall 
JavaCall.init(["-Djava.class.path=/home/eyota/Documents/JuliaTestProject/mypackage.jar"])

jouter=@jimport mypackage.Outer
jinner=@jimport mypackage.Outer$Inner

outerObj= jouter((),)
innerObj=jcall(outerObj, "createrInnerObject", jinner,())
jcall(innerObj, "innerMethod", Void,()) 
`
Error:
`ERROR: LoadError: Class Not Found mypackage/Outer`

**Comment by dfdx** [comment]
How did you create `mypackage.jar`? I've just tested your code and it worked perfectly well. Make sure your `.jar` file has structure like this:

```
$ unzip -l mypackage.jar 
Archive:  mypackage.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2018-05-24 20:45   META-INF/
       69  2018-05-24 20:45   META-INF/MANIFEST.MF
      395  2018-05-24 20:44   mypackage/Outer.class
      558  2018-05-24 20:44   mypackage/Outer$Inner.class
---------                     -------
     1022                     4 files
```

**Comment by Eyota** [comment]
You are right, my package.jar was not structured correctly... I works now.
Thank you very much for your help!

**Comment by KeithWM** [comment]
I think I'm facing the same issue as Eyota was. How exactly should the jar be created? I'm not seeing `Outer.class` nor `Outer$Inner.class`, only `Outer` without the class suffix.

**Comment by mkitti** [comment]
It sounds to me that you are facing a Java issue rather than a JavaCall.jl issue.

Anyways, feel free to open a new issue if you think there is a JavaCall.jl related issue.

**Comment by KeithWM** [comment]
Thanks for the swift response. Could you maybe give the command for creating the jar? Do I need to use/avoid any compiler flags.

**Comment by dfdx** [comment]
Take a look at [this](https://www.baeldung.com/java-create-jar) tutorial (points from 1 to 3.1). Creating a jar is no magic - internally it's just a zip archive with certain structure - but depending on your use case exact instructions may vary, so it's worth to understand the matter.

**Comment by KeithWM** [comment]
Thanks a lot, that really helped. As a complete novice to Java I had assumed jar did both the compilation and packaging, so my jar did not contain the correct .class files of the most recent compilation.
