### ISSUE TITLE
[OSX] using JavaCall works, JavaCall.init fails

### ISSUE THREAD

**Issue by adufour** [JuliaInterop/JavaCall.jl#57]
I am running Julia 0.5.2 on macOS Sierra with Oracle's JDK 8 (121) installed.

My /usr/libexec/java_home points to the correct place 
```shell
shell> /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home
```
And my java works:
```julia
shell> /usr/bin/java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
The following call therefore works:
```julia
julia> using JavaCall
Loaded /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/server/libjvm.dylib
```
Alas, the subsequent call fails:
```julia
julia> JavaCall.init()
signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
unknown function (ip: 0x3162db2b3)
Allocations: 2823173 (Pool: 2822149; Big: 1024); GC: 2
No Java runtime present, requesting install.
```
Followed by the classic macOS popup indicating that Apple's Java (i.e. 6) is required but missing.

Any clue why this could happen? (I have to mention that this is fresh new system/OS, Java 6 was never installed/deleted after some OS upgrade)

**Comment by aviks** [comment]
Yeah, this is a JVM bug. Apple has removed the system JVM (1.6)  in recent versions of MacOS, but the Oracle VM assumes that it exists. Only workaround is to download and install the 1.6 JVM from Apple. More info in the JavaCall FAQ: http://juliainterop.github.io/JavaCall.jl/faq.html

**Comment by adufour** [comment]
My apologies for not having caught this on the FAQ. took mistake. Cheers!

**Comment by aviks** [comment]
No problem. Hope JavaCall does what you need, apart from this hitch.
