### ISSUE TITLE
wildcard in JavaCall.addClassPath

### ISSUE THREAD

**Issue by KenziTrader** [JuliaInterop/JavaCall.jl#58]
According to https://docs.oracle.com/javase/8/docs/technotes/tools/windows/classpath.html the class path entries can contain the base name wildcard character (*), which is considered equivalent to specifying a list of all of the files in the directory with the extension .jar or .JAR.

Using `JavaCall.addClassPath("directory/lib/*")` doesn't work. I have to explicitly add every .jar to the class path.

Can wildcards be added?

**Comment by aviks** [comment]
Hi @KenziTrader 

I added the facility to add wildcards in classpath in this commit: https://github.com/JuliaInterop/JavaCall.jl/commit/33604ff332bce4c130e2efe7717534303e14c3f8

You should have it in the latest release version of JavaCall, currently `0.5.0`. However, looking at this code just now, I realised it wouldn't work in windows. So if you're using windows, you'll have to wait for a few days till I fix it.

**Comment by KenziTrader** [comment]
I upgraded to version `0.5.0` and the wildcard works. Thanks!
