### ISSUE TITLE
Path added with `addClassPath` ignored by `init(opts)` method

### ISSUE THREAD

**Issue by nicolaspayette** [JuliaInterop/JavaCall.jl#59]
I tried to do something like this:

```julia
JavaCall.addClassPath("/mypath/*")
JavaCall.init(["-Xmx512M"])
```

It took me a while to understand why my class path was ignored.

You need to do either: 

```julia
JavaCall.init(["-Xmx512M", "-Djava.class.path=/mypath/*"])
```

or:

```julia
JavaCall.addClassPath("/mypath/*")
JavaCall.addOpts("-Xmx512M")
JavaCall.init()
```

It would be nice if `init(opts)` honored paths added via `addClassPath` (though this raises the question of what to do if the user _also_ includes `"-Djava.class.path=..."` in `opts`). Short of that, maybe the docs could mention the possible gotcha.

**Comment by mkitti** [comment]
As of 141df7d (should be in v0.7.4) the behavior is now as follows:
```
julia> using JavaCall

julia> JavaCall.addClassPath("foo")

julia> JavaCall.init(["-Xmx512M","-Djava.class.path=bar"])

julia> JavaCall.getClassPath()
"foo:bar"
```
