### ISSUE TITLE
broken conversion from `java.sql.Date`

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaInterop/JavaCall.jl#72]
At least I *think* it's broken.
```julia
jsd = @jimport(java.sql.Date)((jlong,),0)
convert(DateTime, jsd)  # returns 1969-12-31T20:00:00
```
I was expecting "1970-01-01T00:00:00".  Is this some time zone issue?

There seems to be a problem in JDBC.jl where some time conversions are off by an hour (that's right, 1 hour, not 4).

**Comment by aviks** [comment]
What timezone is your machine set to?

**Comment by ExpandingMan** [comment]
US Eastern.  I'm pretty sure it is indeed a timezone issue, so I guess it's probably not a "bug".

Ah date-time... the only thing that can cause bugs based on your location in the world.  Ugh, what a terrible way of keeping time.

Assuming this *is* time-zone, I'm not sure what other action can be taken other than just ignoring it.  I suppose we could plan to make a Julia `struct` with timezone, but that seems like it may be more trouble than it's worth.

**Comment by mkitti** [comment]
This looks like a time zone issue. I get this from US Central time
```
julia> using JavaCall, Dates

julia> JavaCall.init()

julia> jsd = @jimport(java.sql.Date)((jlong,),0)
JavaObject{Symbol("java.sql.Date")}(Ptr{Nothing} @0x0000000002849be8)

julia> convert(DateTime, jsd)
1969-12-31T19:00:00
```

**Comment by aviks** [comment]
Yeah, I'll close this now.
