### ISSUE TITLE
jcall a method that returns void

### ISSUE THREAD

**Issue by sorokod** [JuliaInterop/JavaCall.jl#82]
Hello

How do I `jcall` a method that returns void? I tried `jcall(jimported,  "methodName"   ,  Void   , (<argument types>), <argument values>)` but got `ERROR: UndefVarError: Void not defined`

**Comment by dfdx** [comment]
Try `Nothing` instead of `Void`.

**Comment by sorokod** [comment]
Thanks for Nothing
