### ISSUE TITLE
test failure on Java 10: JString methods

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaInterop/JavaCall.jl#88]
Line 172 of `runtests.jl` is failing on Julia 1.0.0, Java 10.0.2.
```julia
method_lists_1: Test Failed at /home/expandingman/.julia/dev/JavaCall/test/runtests.jl:176
  Expression: [getname(typ) for typ = getparametertypes(m)] == ["int"]
   Evaluated: ["java.lang.String", "int"] == ["int"]
```
So, I'm getting what the tests claim is the correct behavior for Java versions lower than 9.0.0.

My guess is that the tests are probably wrong, and it's ok for later Java versions to return this, and that we should change the test to pass if it's either or.

Does anyone know any more about this?

**Comment by mkitti** [comment]
Tests are passing on Java 11 so closing.
