### ISSUE TITLE
StackOverflowError in `JavaCall.init` for Julia 1.1.0

### ISSUE THREAD

**Issue by KenziTrader** [JuliaInterop/JavaCall.jl#96]
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using JavaCall

julia> JavaCall.init(["-Xmx128M"])

signal (11): Segmentation fault: 11
in expression starting at no file:0
unknown function (ip: 0x122b242b3)
Allocations: 2501680 (Pool: 2501183; Big: 497); GC: 4
ERROR: StackOverflowError:
Stacktrace:
 [1] init(::Array{String,1}) at /Users/rene/.julia/packages/JavaCall/toamy/src/jvm.jl:176
 [2] top-level scope at none:0
```

**Comment by karikoskinen** [comment]
Similar problem here, but instead of segfault, is just hangs indefinitely. By putting those lines in a file and running julia, it works.

```
$ cat initjavacall.jl
using JavaCall
JavaCall.init(["-Xmx128m"])
println("JavaCall initialized")

$ julia -i initjavacall.jl
JavaCall initialized
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0 (2019-01-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia>
```

**Comment by aviks** [comment]
This seems to be a bigger issue than I thought. For now, I would advice all users of JavaCall and its derivatives stick to Julia 1.0.x

**Comment by elinder912** [comment]
Could this bug be related: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8222409

**Comment by ExpandingMan** [comment]
Great news all, Jeff just merged a [PR he made for 1.3](https://github.com/JuliaLang/julia/pull/32885).  So it looks like we'll be back up and running with 1.3.  I'm not quite sure what the implications are of setting this environment variable, at the very least I think it means somewhat inefficient multi-threading.  However, at least it will get applications that need to use the JVM unstuck.

**Comment by kcajf** [comment]
Hadn't noticed that PR - great news. I would also be interested in hearing from someone with a bit more knowledge about the system as to how `JULIA_COPY_STACKS=1` will affect performance on different threading workloads.

**Comment by aviks** [comment]
Guess what? It looks like JDK 11 works with all versions of Java. Proof: https://travis-ci.org/JuliaInterop/JavaCall.jl/builds/588468061

**Comment by mkitti** [comment]
Using openjdk version 11.0.6 and Julia 1.3.1 makes JavaCall work with scripts. However, once the REPL starts, things do not work.

I slightly expanded the script above to include a test from the documentation.

```
$ cat initjavacall.jl 
using JavaCall
JavaCall.init(["-Xmx128m"])
println("JavaCall initialized")
jlm = @jimport java.lang.Math
out = jcall(jlm, "sin", jdouble, (jdouble,), pi/2)
println(out)
```

The test appears to work correctly on startup. However, once the REPL gets going, the call no longer seems to work correctly.

```
$ julia --banner=no -i initjavacall.jl 
JavaCall initialized
1.0
julia> jcall(jlm, "sin", jdouble, (jdouble,), pi/2)
0.0
```

Here is the openjdk version I am using on Ubuntu 18.04.

```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
```

**Comment by mkitti** [comment]
Setting `JULIA_COPY_STACKS=yes` makes things work properly.

```
$ JULIA_COPY_STACKS=yes julia --banner=no -i initjavacall.jl 
JavaCall initialized
1.0
julia> jcall(jlm, "sin", jdouble, (jdouble,), pi/2)
1.0
```

**Comment by aviks** [comment]
So yes, to use JavaCall, you need to use Julia 1.0, or Julia 1.3 with `JULIA_COPY_STACKS=1`. This is due to how Java uses the stack, and a change to Julia's stack mechanism in 1.1 to improve threading performance. This is now documented, and `using JavaCall` will warn you when running in an unsupported environment. Thanks for bearing with us on this - but I think now the situation is settled.
